"""table: create <order_item> <order_payment> <order_review>

Revision ID: 1d82d0d9ec4f
Revises: 1f5167b28fc2
Create Date: 2026-04-16 15:13:51.880507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d82d0d9ec4f'
down_revision: Union[str, Sequence[str], None] = '1f5167b28fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderitem',
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seller_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shipping_limit_date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('freight_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.seller_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'order_item_id')
    )
    op.create_table('orderpayment',
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_sequential', sa.Integer(), nullable=False),
    sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_installment', sa.Integer(), nullable=True),
    sa.Column('payment_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'payment_sequential')
    )
    op.create_table('orderreview',
    sa.Column('review_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review_score', sa.Integer(), nullable=True),
    sa.Column('review_comment_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_comment_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_creation_date', sa.DateTime(), nullable=True),
    sa.Column('review_answer_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderreview')
    op.drop_table('orderpayment')
    op.drop_table('orderitem')
    # ### end Alembic commands ###
