"""table: create <order>

Revision ID: 1f5167b28fc2
Revises: ac73a3a91d9a
Create Date: 2026-04-16 15:13:16.325940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f5167b28fc2'
down_revision: Union[str, Sequence[str], None] = 'ac73a3a91d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_purchase_timestamp', sa.DateTime(), nullable=True),
    sa.Column('order_approved_at', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_carrier_date', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_customer_date', sa.DateTime(), nullable=True),
    sa.Column('order_estimated_delivery_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
