"""table: create <product> <customer> <seller>

Revision ID: ac73a3a91d9a
Revises: 530b514dc9a3
Create Date: 2026-04-16 15:12:53.079308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac73a3a91d9a'
down_revision: Union[str, Sequence[str], None] = '530b514dc9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_unique_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_zipcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['customer_zipcode'], ['geolocation.zipcode'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('product',
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=True),
    sa.Column('product_name_length', sa.Integer(), nullable=True),
    sa.Column('product_description_length', sa.Integer(), nullable=True),
    sa.Column('product_photos_qty', sa.Integer(), nullable=True),
    sa.Column('product_weight_g', sa.Integer(), nullable=True),
    sa.Column('product_length_cm', sa.Integer(), nullable=True),
    sa.Column('product_height_cm', sa.Integer(), nullable=True),
    sa.Column('product_width_cm', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('seller',
    sa.Column('seller_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seller_zipcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seller_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seller_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['seller_zipcode'], ['geolocation.zipcode'], ),
    sa.PrimaryKeyConstraint('seller_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller')
    op.drop_table('product')
    op.drop_table('customer')
    # ### end Alembic commands ###
