"""create product table

Revision ID: e65e584d94b8
Revises: 8b143b3d7424
Create Date: 2026-04-11 15:23:17.730215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e65e584d94b8'
down_revision: Union[str, Sequence[str], None] = '8b143b3d7424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_name_length', sa.Integer(), nullable=True),
    sa.Column('product_description_length', sa.Integer(), nullable=True),
    sa.Column('product_photos_qty', sa.Integer(), nullable=True),
    sa.Column('product_weight_g', sa.Integer(), nullable=True),
    sa.Column('product_length_cm', sa.Integer(), nullable=True),
    sa.Column('product_height_cm', sa.Integer(), nullable=True),
    sa.Column('product_width_cm', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_category_name'], ['category.name'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
